### ISSUE TITLE
Add Get-WorkItemQueryResult cmdlet?

### ISSUE THREAD

**Issue by MarkIannucci** [StartAutomating/PSDevOps#63]
We're looking to synchronize the work items in Azure DevOps with another system that we cannot control, and we're thinking that we can use your module to do so.  I'm going to start exploring the [Wiql - Query By Wiql](https://docs.microsoft.com/en-us/rest/api/azure/devops/wit/wiql/query%20by%20wiql?view=azure-devops-rest-6.0) endpoint to make that work in our organization.  

I thought I'd simultaneously open this issue since I noticed that PSDevOps does not have a Get-WorkItemQueryResult cmdlet.  I'm not sure if the stub I build out will be helpful but wanted to get your thoughts on the feasibility of adding this cmdlet to your module.

Are you interested in that sort of contribution?  Also any hints as I start setting up a development environment?

**Comment by MarkIannucci** [comment]
I am quite happy I read your code before writing my own.  I think `Get-WorkItem` has me covered!

**Comment by StartAutomating** [comment]
@MarkIannucci thanks for closing this issue before I go around to pointing you in that general direction.

A few things to note:

* Get-ADOWorkItem (and a lot of PSDevOps) return data that can be reformatted for your Org/Project.  If you would like to see your work item differently than PSDevOps does by default, I'd love to know.
* There are actually two different types of formatters for work items.  You'll see the table formatter by default.  A "custom" formatter can show you a more detailed view of a given work item (including descriptions, for instance).  To show details of a particular work item, pipe it to Format-Custom.
* The related commands, New/Set-ADOWorkItem, will both be so kind as to try to adapt incoming properties.  So you can @{Description='New Description'} | Set-ADOWorkItem -ID $id instead of @{'System.Description'='New Description'} | Set-ADOWorkItem -ID $id

Feel free to file issues if you have them with these commands.  They are relatively old compared to various other parts of PSDevOps, and are due for a bit of extensibility.

**Comment by MarkIannucci** [comment]
So far, this cmdlet has met our needs.  I think I found a slight issue with the way it inserts the `[Team Project] = @Project` in the where clause.  I'll double check my theory on the bug before I prematurely open another issue ;-)

Again, thank you for your work here.  We're using this at a public hospital in Denver to improve our IT system management processes, so know that this code helps us help others.
